import type { Metadata } from "next";
import "../../globals.css";
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/Sidebar/AppSidebar"
import Header from "@/components/Header/Header";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>

        <SidebarProvider>

          <AppSidebar />
          <main className=" w-full h-dvh border bg-zinc-900">
            <Header />
            {children}
          </main>
        </SidebarProvider>


      </body>
    </html>
  );
}
